server:
  port: 8080
  servlet:
    context-path: /iss
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iss_airline_db
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      add-mappings: true

  flights:
    status:
      update-interval-ms: 10000
      on-time-window-hours: 1

aircraft:
  maintenance:
    threshold-hours: 500
    period-days: 180
    check-interval-ms: 60000

logging:
  level:
    org.thymeleaf: DEBUG
    org.springframework.web: DEBUG
