server:
  port: 8080
  servlet:
    context-path: /iss
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iss_airline_db
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

flights:
  status:
    update-interval-ms: 30000
    on-time-window-hours: 1

aircraft:
  maintenance:
    threshold-hours: 500
    period-days: 180
    check-interval-ms: 300000
